#!/usr/bin/env python3
"""
Simple instructions for creating a test user
"""

print("=== AccessoryHub Test User Creation Instructions ===")
print()
print("Since the registration is now working, please create a test user through the web interface:")
print()
print("1. Start your Flask application:")
print("   cd /home/brandon/Desktop/accesoryhub")
print("   source venv/bin/activate")
print("   python app.py")
print()
print("2. Open your browser and go to:")
print("   http://localhost:5000")
print()
print("3. Click on 'Register' link")
print()
print("4. Fill out the registration form with these details:")
print("   Name: Test User")
print("   Email: testuser@yourdomain.com (use any valid email)")
print("   Password: testuser123")
print()
print("5. Submit the form")
print()
print("6. If you get an email confirmation prompt, check your email")
print()
print("7. After registration, login with:")
print("   Email: (whatever you used)")
print("   Password: testuser123")
print()
print("Alternative - Use a simple test email:")
print("   Name: John Doe")
print("   Email: john.doe@example.com")
print("   Password: password123")
print()
print("Once logged in, you'll have access to:")
print("- Browse products")
print("- Add items to cart")
print("- Place orders")
print("- View your orders")
print()
print("For admin access, use:")
print("   Email: testadmin@accesoryhub.com")
print("   (You may need to set up this admin account separately)")

